language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

env:
  matrix:
    - PIP_FLAGS="--quiet"
    - PIP_FLAGS="--quiet --pre"

matrix:
  allow_failures:
    - env: PIP_FLAGS="--quiet --pre"
  fast_finish: true

before_install:
  - python -m pip install ${PIP_FLAGS} --upgrade pip
  - python -m pip install ${PIP_FLAGS} "pytest>=2.8" pytest-cov unittest2
  - python -m pip install ${PIP_FLAGS} -r requirements.txt

install:
  # note: need --editable for coverage with `which ...` to work
  - python -m pip install --editable .

script:
  - python -m coverage run -m pytest omicron/
  - python -m coverage run -a $(which omicron-process) --help
  - python -m coverage run -a $(which omicron-status) --help

after_success:
  - coveralls

cache:
  pip: true
