language: python

addons:
  apt:
    packages:
      - python-m2crypto  # glue

matrix:
  include:
    - python: 2.6
      PRE=""
    - python: 2.7
      PRE=""
    - python: 2.7
      env: PRE="--pre" GWPY="git+https://github.com/gwpy/gwpy.git"
  allow_failures:
    - python: 2.7
      env: PRE="--pre" GWPY="git+https://github.com/gwpy/gwpy.git"

before_install:
  - pip install -q --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - pip install .

cache:
  - pip
  - apt
