language: python

addons:
  apt:
    packages:
      - gcc  # numpy/scipy
      - gfortran  # numpy/scipy
      - libblas-dev  # numpy/scipy
      - liblapack-dev  # numpy/scipy
      - python-m2crypto  # glue

matrix:
  include:
    - python: 2.6
      env: PRE=""
    - python: 2.7
      env: PRE=""
    - python: 2.7
      env: PRE="--pre" GWPY="git+https://github.com/gwpy/gwpy.git"
  allow_failures:
    - python: 2.7
      env: PRE="--pre" GWPY="git+https://github.com/gwpy/gwpy.git"

before_install:
  - pip install -q --upgrade pip
  - pip install -q ${PRE} coveralls "pytest>=2.8" unittest2

install:
  - pip install -r requirements.txt
  - python setup.py build

script:
  - coverage run --source=omicron --omit="omicron/tests/*,omicron/version.py" -m py.test -v omicron/
  - pip install .

cache:
  - pip
  - apt
