# conda dependencies for pyomicron
# please try and keep this synchronised with requirements.txt

name: pyomicron
channels:
  - conda-forge
dependencies:
  - dqsegdb2
  - gwdatafind
  - gwpy >=1.0.0
  - h5py
  - htcondor
  - ligo-segments
  - lscsoft-glue >=1.60.0
  - markuppy
  - numpy
  - omicron >=2.3.12
  - python
  - python-ldas-tools-framecpp
  - python-ligo-lw >=1.4.0
  - root_base 6.18.04
